import type { FarmProfile } from "@/lib/packs/types";
import { tamilNaduAgroforestry } from "@/lib/profiles/biomes";

export const samanyaProfile: FarmProfile = {
  id: "samanya",
  name: "ET Samanya Farms",
  shortName: "Samanya",
  legalName: "ET Samanya Foods Private Limited",
  timezone: "Asia/Kolkata",
  currency: "INR",
  units: "metric",
  languages: ["en", "ta"],
  location: {
    lat: 12.1123294,
    lng: 79.6467758,
    village: "Thenkulapakkam",
    address: "East Street, Thenkulapakkam, Tamil Nadu 604304",
    timezone: "Asia/Kolkata",
  },
  acres: 5,
  treeCensusTarget: 1600,
  animalCensusTarget: null,
  bedCensusTarget: null,
  enabledPacks: ["agroforestry", "horticulture", "livestock", "water", "permaculture", "stay", "energy"],
  publicSite: true,
  biomeId: tamilNaduAgroforestry.id,
  harvestCrops: tamilNaduAgroforestry.harvestCrops,
  harvestDestinations: ["House", "Gift", "Sale"],
  seedSpecies: tamilNaduAgroforestry.seedSpecies,
  seedPlots: tamilNaduAgroforestry.seedPlots,
  zoneLabels: tamilNaduAgroforestry.zoneLabels,
  kitItems: tamilNaduAgroforestry.kitItems,
  kitStatuses: ["On", "Off", "Fault", "Borrowed", "Fixed"],
  activityTypes: ["Walk", "Workshop", "Picnic", "Stay day", "Labour", "Other"],
  ledgerCategories: ["Seed", "Labour", "Diesel", "Feed", "Kit", "Produce sold", "Other"],
  pondLevels: ["Low", "Ok", "High"],
  defaultAnimalKind: tamilNaduAgroforestry.defaultAnimalKind,
  rules: tamilNaduAgroforestry.rules,
  onboardedAt: "2022-01-01T00:00:00.000Z",
};

export function blankFarmProfile(): FarmProfile {
  return {
    id: "farm",
    name: "New farm",
    shortName: "Farm",
    legalName: null,
    timezone: "Asia/Kolkata",
    currency: "INR",
    units: "metric",
    languages: ["en"],
    location: {
      lat: 12.1123294,
      lng: 79.6467758,
      village: "",
      address: "",
      timezone: "Asia/Kolkata",
    },
    acres: null,
    treeCensusTarget: null,
    animalCensusTarget: null,
    bedCensusTarget: null,
    enabledPacks: ["horticulture", "water"],
    publicSite: false,
    biomeId: "vegetables-only",
    harvestCrops: [],
    harvestDestinations: ["House", "Gift", "Sale"],
    seedSpecies: [],
    seedPlots: [],
    zoneLabels: ["House", "Beds", "Water", "Edges"],
    kitItems: ["Pump", "Drip", "Tank", "Tool", "Other"],
    kitStatuses: ["On", "Off", "Fault", "Borrowed", "Fixed"],
    activityTypes: ["Walk", "Workshop", "Labour", "Other"],
    ledgerCategories: ["Seed", "Labour", "Feed", "Kit", "Produce sold", "Other"],
    pondLevels: ["Low", "Ok", "High"],
    defaultAnimalKind: "Cattle",
    rules: [],
    onboardedAt: null,
  };
}
